### ISSUE TITLE
Improve GitHub workflows

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#162]
I think there are some improvements possible within the GitHub workflows. In some of the GitHub workflows we run PHP_CodeSniffer in a PHP matrix strategy with just one PHP version. Can we drop the matrix strategy?

- https://github.com/pronamic/wp-pay-core/blob/develop/.github/workflows/main.yaml
- https://github.com/wp-pay-gateways/omnikassa-2/blob/master/.github/workflows/main.yaml

Is it also better to combine PHP_CodeSniffer, PHPStan, etc. in one job? Will this reduce build minutes? Or is it better to keep it separate?

Currently we test almost every library with alle WordPress versions from `4.7` to the latest release. Does this add value because we rarely have tests for specific WordPress versions?

And should we also try to move away from completely setting up a WordPress environment more often? Maybe we could use something like: https://github.com/Automattic/wordbless.

> WorDBless allows you to use WordPress core functions in your PHPUnit tests without having to set up a database and the whole WordPress environment

We got feedback on improving the GitHub workflow once before in https://github.com/pronamic/wp-pay-core/issues/16.

- https://github.com/szepeviktor/phpstan-wordpress
- https://github.com/php-stubs/wordpress-stubs
- https://github.com/Brain-WP/BrainMonkey
- https://github.com/Yoast/PHPUnit-Polyfills
- https://github.com/woocommerce/phpunit

Already tried to improve some of this in https://github.com/pronamic/wp-number/blob/main/.github/workflows/main.yml, but still searching for the best practice.

Maybe we should also introduce a repository like https://github.com/yoast/wp-test-utils for a more DRY approach. Or should we build our own GitHub action that we can reuse?

**Comment by remcotolsma** [comment]
We also have the same matrix in a lot of the WordPress projects:

```
    strategy:
      fail-fast: false
      matrix:
        include:
          # PHP Compatibility and WordPress Versions: https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
          - name: WP 5.7
            php-version: 7.4
            wp-version: 5.7.*
          - name: WP 5.6
            php-version: 7.4
            wp-version: 5.6.*
          - name: WP 5.5
            php-version: 7.4
            wp-version: 5.5.*
          # WordPress and PHP 7.4: https://make.wordpress.org/core/2019/10/11/wordpress-and-php-7-4/.
          - name: WP 5.4
            php-version: 7.4
            wp-version: 5.4.*
          - name: WP 5.3
            php-version: 7.4
            wp-version: 5.3.*
          # WordPress 5.2 (or lower) will trigger PHP 7.4 (or higher) errors.
          # @link https://make.wordpress.org/core/2019/10/11/wordpress-and-php-7-4/.
          - name: WP 5.2
            php-version: 7.3
            wp-version: 5.2.*
          - name: WP 5.1
            php-version: 7.3
            wp-version: 5.1.*
          - name: WP 5.0
            php-version: 7.3
            wp-version: 5.0.*
          - name: WP 4.9
            php-version: 7.3
            wp-version: 4.9.*
          # WordPress 4.8 (or lower) will trigger PHP 7.2 (or higher) errors.
          # @link https://make.wordpress.org/core/2018/10/15/wordpress-and-php-7-3/
          # @link https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/
          # @link https://make.wordpress.org/core/tag/4-9/?s=7.2
          - name: WP 4.8
            php-version: 7.1
            wp-version: 4.8.*
            phpunit-version: ^6
          - name: WP 4.7
            php-version: 7.1
            wp-version: 4.7.*
            phpunit-version: ^6
          - name: Multisite
            php-version: 7.4
            WP_MULTISITE: 1
          - php-version: 7.4
          - php-version: 7.3
          - php-version: 7.2
          - php-version: 7.1
          - php-version: 7.0
          - php-version: 5.6
            phpunit-version: ^5
```

This is related to the "Supported Version Chart" on https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/:

![make wordpress org_core_handbook_references_php-compatibility-and-wordpress-versions_](https://user-images.githubusercontent.com/869674/123265764-aa103200-d4fb-11eb-9a01-be74802d124a.png)

It looks like it is possible to load a matrix from JSON:

- https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script
- https://stackoverflow.com/questions/65056670/is-it-possible-to-have-a-dynamic-strategy-matrix-in-a-workflow-in-github-actions
- https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson

**Comment by remcotolsma** [comment]
I did some work in https://github.com/pronamic/wp-pronamic-pay-omnikassa-2/blob/develop/.github/workflows/ci.yml.

```
name: CI

on: [ push, pull_request ]

jobs:
  phplint:
    uses: pronamic/actions/.github/workflows/phplint.yml@main

  phpcs:
    uses: pronamic/actions/.github/workflows/phpcs.yml@main

  phpstan:
    uses: pronamic/actions/.github/workflows/phpstan.yml@main

  psalm:
    uses: pronamic/actions/.github/workflows/psalm.yml@main

  phpunit:
    uses: pronamic/actions/.github/workflows/phpunit.yml@main

  coverage:
    uses: pronamic/actions/.github/workflows/coverage.yml@main
```

https://github.com/pronamic/actions/tree/main/.github/workflows

This approach is a little more DRY.

I would also like to propose that from now on we will only support the 3 latest **minor** `MAJOR.MINOR.PATCH` versions of PHP and WordPress.

```
php-versions: ['7.4', '8.0', '8.1']
wp-versions: ['5.7', '5.8', '5.9']
```

I don't think we need to implement this directly in all repositories, as soon as we work on an integration we can update the relevant repository.

https://github.com/Yoast/PHPUnit-Polyfills
